services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-devops
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - ./workspace:/workspace
    tty: true
    stdin_open: true
    platform: linux/arm64
  postgres:
    image: postgres:latest
    container_name: postgres-arm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/etc/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-arm
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pgdata: