version: "3.9"

services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-devops
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - ./workspace:/workspace

    tty: true
    stdin_open: true

    platform: linux/arm64